version: '3'
services:
    server:
        build: 
            context: ./server
        container_name: server
        ports:
            - '5000:5000'
    client:
        build:
            context: ./client
        container_name: client
        ports:
            - '80:3000'
